squash it all
karimsa/sidekick pull request #50
Opened 2022-09-23 17:58 UTC by A1Liu

2022-09-24 17:18 UTC, karimsa requested changes

2022-09-24 17:18 UTC, karimsa commented on server/utils/channel.ts
> +			// better to just make sure a call to destroy can only happen once
That's fine, but probably want to at least log that it happened

2022-09-24 17:18 UTC, karimsa commented on server/utils/channel.ts
> +				this.reader = [resolve, reject];
Lol why not an object? the `this.reader?.[1]?.()` is hard to read

2022-12-20 04:40 UTC, A1Liu commented on server/utils/channel.ts
> +				this.reader = [resolve, reject];
it is now an object

2022-12-20 04:44 UTC, A1Liu commented on server/utils/channel.ts
> +			// better to just make sure a call to destroy can only happen once
done

2022-12-20 04:44 UTC, A1Liu commented on server/services/service-builds.ts
> +		// );
done

2022-12-20 05:05 UTC, merged